// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD627pApSoUmy1VrnTgYoxDzz3mzfYiN7Y',
    appId: '1:296683188665:web:35f0b023b5b3a3c0da4668',
    messagingSenderId: '296683188665',
    projectId: 'lopy-2f6e9',
    authDomain: 'lopy-2f6e9.firebaseapp.com',
    storageBucket: 'lopy-2f6e9.appspot.com',
    measurementId: 'G-BF0ZD6EC81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_F7BlNtBCz80XCm0OMJ5dpzmmvj6dR4',
    appId: '1:296683188665:android:8a368875021a8c86da4668',
    messagingSenderId: '296683188665',
    projectId: 'lopy-2f6e9',
    storageBucket: 'lopy-2f6e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAexOfMre0ZBZ18MHrWSPd45LWiQvVRFN4',
    appId: '1:296683188665:ios:1f5e1f004473cc8eda4668',
    messagingSenderId: '296683188665',
    projectId: 'lopy-2f6e9',
    storageBucket: 'lopy-2f6e9.appspot.com',
    iosBundleId: 'com.lopy.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAexOfMre0ZBZ18MHrWSPd45LWiQvVRFN4',
    appId: '1:296683188665:ios:40bce3f233b51f5bda4668',
    messagingSenderId: '296683188665',
    projectId: 'lopy-2f6e9',
    storageBucket: 'lopy-2f6e9.appspot.com',
    iosBundleId: 'com.lopy.food.RunnerTests',
  );
}
